language: node_js
sudo: false
node_js:
  - 10

install: yarn install

script: yarn test

after_success: yarn build

deploy: 
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "nirr-static-blujay"
  skip_cleanup: true
  region: eu-central-1
  local_dir: build
  on:
    branch: master