language: node_js
sudo: false
node_js:
  - 10

jobs:
  include:
    - stage: test
      install: yarn install
    - script: yarn test
    - stage: deploy
      install: yarn build
      provider: s3
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY
      bucket: "S3 Bucket"
      skip_cleanup: true
      region: eu-west-1
      local_dir: build

stages:
  - test
  - name: deploy
    if: branch = master