language: node_js
sudo: false
node_js:
  - 10

jobs:
  include:
    - stage: install
      script: yarn install
    - stage: test
      script: yarn test
    - stage: build
      script: yarn build
    - stage: deploy
      provider: s3
      access_key_id: "YOUR AWS ACCESS KEY"
      secret_access_key: "YOUR AWS SECRET KEY"
      bucket: "S3 Bucket"
      skip_cleanup: true
      region: eu-west-1
      local_dir: build

stages:
  - install
  - test
  - build
  - name: deploy
    if: branch = master